Home mobile
Revature-RPM/ng-ui pull request #262
Opened 2019-06-07 17:32 UTC by jeffreyzarate

2019-06-07 17:50 UTC, BrandonSlade approved these changes
Everything looks fine.

2019-06-07 19:17 UTC, mgoshorn approved these changes

2019-06-07 19:17 UTC, mgoshorn commented on src/app/project/view-projects-logic/view-projects-logic.component.scss
> +  // tbody {
Remove commented out rules

2019-06-07 19:17 UTC, mgoshorn commented on src/app/project/view-projects-logic/view-projects-logic.component.scss
> +  #project-image
Keep formatting of rules consistent

2019-06-07 19:17 UTC, mgoshorn commented on src/app/project/view-users-projects/view-users-projects.component.scss
> +    // tbody {
Remove commented out rules

2019-06-07 19:18 UTC, mgoshorn requested changes
@jeffreyzarate See above notes

2019-06-10 13:52 UTC, mgoshorn approved these changes

2019-06-10 13:52 UTC, merged