added restriction for editing projects
Revature-RPM/ng-ui pull request #340
Opened 2019-08-06 17:53 UTC by ahodge10

Complete functionality for editing projects based on ownership of project and Admin role, but code is dependent on the approval of implementation from other user stories.

2019-08-06 18:25 UTC, jurczakn requested changes
Add a test for the display of the update project button.

2019-08-08 15:10 UTC, ahodge10 commented
Changes addressed. Merge conflict resolved.

2019-08-12 13:51 UTC, ahodge10 commented
conflicts resolved

2019-08-12 14:20 UTC, jurczakn requested changes

2019-08-12 14:20 UTC, jurczakn commented on src/app/components/pages/project/project-grid-page/project-grid-page.component.html
> +                </div> -->
Remove leftover end comment

2019-08-12 14:57 UTC, jurczakn approved these changes
ok

2019-08-12 14:57 UTC, merged